version: '3.2'

services :
  zookeeper:
    image : confluentinc/cp-zookeeper:latest
    restart : always
    hostname : zookeeper
    networks:
      - messaging-network
    ports : 
      - 2181:2181
    environment : 
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka : 
    image : confluentinc/cp-kafka:latest
    hostname : kafka
    depends_on : 
      - zookeeper
    networks:
      - messaging-network
    ports : 
      - 9092:9092
    environment: 
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  producer:
    restart: always
    build: ./producer
    depends_on : 
      - kafka
    networks:
      - messaging-network
    ports:
      - 8082:8080
  consumer:
    restart: always
    build: ./consumer
    networks:
      - messaging-network
    depends_on : 
      - kafka
    ports:
      - 8081:8080
networks:
  messaging-network: 