spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
           - localhost:9092
           - kafka:9092
      bindings:
        input:
         destination: test
         group: input-group-1